import PDFDocument from 'pdfkit'
import { Buffer } from 'buffer'

import type { Issue, RoomInspection, FloorCoverage, ReportData } from './types'


// ✅ Correct function signature: (data: ReportData, date: string)
export async function generatePDF(data: ReportData, date: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 50, bottom: 50, left: 40, right: 40 },
      })

      const chunks: Buffer[] = []
      doc.on('data', (chunk: Buffer) => chunks.push(chunk))
      doc.on('end', () => resolve(Buffer.concat(chunks)))
      doc.on('error', reject)

      let currentPage = 1

      // Helper to add header on each page
      const addHeader = () => {
        doc
          .fontSize(20)
          .font('Helvetica-Bold')
          .fillColor('#B4651E')
          .text('MAHE Daily Facility Report', { align: 'center' })
          .moveDown(0.3)
          .fontSize(11)
          .font('Helvetica')
          .fillColor('#7a6a55')
          .text(`Date: ${new Date(data.date).toLocaleDateString('en-IN', {
            weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
          })}`, { align: 'center' })
          .moveDown(0.5)
          .fontSize(9)
          .text('Manipal Academy of Higher Education', { align: 'center' })
          .moveDown(0.5)

        doc.moveTo(40, doc.y).lineTo(570, doc.y).strokeColor('#B4651E').lineWidth(2).stroke()
        doc.moveDown(0.8)
      }

      // Helper to add footer with page number
      const addFooter = (pageNum: number, total: number) => {
        const originalY = doc.y
        doc
          .moveTo(40, 780)
          .lineTo(570, 780)
          .strokeColor('#B4651E')
          .lineWidth(1)
          .stroke()
          .fontSize(8)
          .font('Helvetica')
          .fillColor('#7a6a55')
          .text(`Page ${pageNum} of ${total}`, 40, 790, { align: 'right', width: 500 })
          .text('Generated by MAHE Facility Management System', 40, 790, { align: 'left', width: 300 })
          .text(`Generated: ${new Date().toLocaleString('en-IN')}`, 40, 800, { align: 'left', width: 300 })
        doc.y = originalY
      }

      // ==================== PAGE 1: HEADER & EXECUTIVE SUMMARY ====================
      addHeader()

      doc
        .fontSize(14)
        .font('Helvetica-Bold')
        .fillColor('#1a1208')
        .text('Executive Summary', { underline: true })
        .moveDown(0.5)

      doc.fontSize(10).font('Helvetica')
      const statsY = doc.y

      doc.fillColor('#1a1208')
        .text('Total Issues Reported:', 50, statsY, { width: 150 })
        .text('Approved Issues:', 50, statsY + 15, { width: 150 })
        .text('Denied Issues:', 50, statsY + 30, { width: 150 })
        .text('Total Rooms Inspected:', 50, statsY + 45, { width: 150 })
        .text('Rooms with Issues:', 50, statsY + 60, { width: 150 })

      doc.font('Helvetica-Bold').fillColor('#B4651E')
        .text(data.summary.total_issues.toString(), 220, statsY, { width: 50 })
        .text(data.summary.approved_issues.toString(), 220, statsY + 15, { width: 50 })
        .text(data.summary.denied_issues.toString(), 220, statsY + 30, { width: 50 })
        .text(data.summary.total_rooms_inspected.toString(), 220, statsY + 45, { width: 50 })
        .text(data.summary.rooms_with_issues.toString(), 220, statsY + 60, { width: 50 })

      doc.moveDown(1)
      doc.font('Helvetica').fillColor('#1a1208')
        .text('Blocks Covered:', { continued: true })
        .font('Helvetica-Bold').fillColor('#B4651E')
        .text(` ${data.summary.blocks_covered.join(', ') || 'None'}`)

      doc.moveDown(1)

      // Floor Coverage Section
      doc
        .fontSize(14)
        .font('Helvetica-Bold')
        .fillColor('#1a1208')
        .text('Floor Coverage Status', { underline: true })
        .moveDown(0.5)

      const checkedFloors = data.floor_coverage.filter((fc: FloorCoverage) => fc.block && fc.floor)

      if (checkedFloors.length > 0) {
        doc.fontSize(10).font('Helvetica').fillColor('#16a34a')
          .text(`✓ ${checkedFloors.length} floors inspected successfully`)
        doc.fillColor('#7a6a55')
          .text(` across blocks ${[...new Set(checkedFloors.map((fc: FloorCoverage) => fc.block))].join(', ')}`)
        doc.moveDown(0.5)

        // Optional: List all checked floors
        doc.fontSize(9).fillColor('#7a6a55')
          .text(`Floors: ${checkedFloors.map((fc: FloorCoverage) => `${fc.block}/F${fc.floor}`).join(', ')}`)
      } else {
        doc.fontSize(10).font('Helvetica').fillColor('#dc2626')
          .text('⚠ No floor inspections recorded today')
        doc.moveDown(0.5)
      }
      // ✅ Show success message if all floors checked
      if (checkedFloors.length > 0 ) {
        doc.fontSize(10).font('Helvetica').fillColor('#16a34a')
          .text(`✓ All ${checkedFloors.length} floors inspected successfully`)
        doc.moveDown(0.5)
      }

      doc.moveDown(1)

      // Room Inspections Summary
      if (data.room_inspections.length > 0) {
        doc
          .fontSize(14)
          .font('Helvetica-Bold')
          .fillColor('#1a1208')
          .text('Room Inspection Summary', { underline: true })
          .moveDown(0.5)

        const inspectionsByBlock = data.room_inspections.reduce((acc: Record<string, RoomInspection[]>, inspection: RoomInspection) => {
          const key = `${inspection.block}-F${inspection.floor}`
          if (!acc[key]) acc[key] = []
          acc[key].push(inspection)
          return acc
        }, {})

        Object.entries(inspectionsByBlock).forEach(([blockFloor, inspections]) => {
          const [block, floor] = blockFloor.split('-F')
          const roomsWithIssues = (inspections as RoomInspection[]).filter((i: RoomInspection) => i.has_issues).length

          doc.fontSize(10).font('Helvetica-Bold').fillColor('#1a1208')
            .text(`Block ${block} - Floor ${floor}`, { continued: true })
          doc.font('Helvetica').fillColor('#7a6a55')
            .text(` - ${inspections.length} rooms inspected`, { continued: true })

          if (roomsWithIssues > 0) {
            doc.fillColor('#dc2626')
              .text(` (${roomsWithIssues} with issues)`)
          } else {
            doc.fillColor('#16a34a')
              .text(' (All clear)')
          }
        })

        doc.moveDown(1)
      }

      // Check if we need a new page
      if (doc.y > 650) {
        addFooter(currentPage, 3)
        doc.addPage()
        currentPage++
        addHeader()
      }

      // ==================== PAGE 2+: APPROVED ISSUES ====================
      doc
        .fontSize(14)
        .font('Helvetica-Bold')
        .fillColor('#1a1208')
        .text('Detailed Issue Report', { underline: true })
        .moveDown(0.5)

      const approvedIssues = data.issues.filter((i: Issue) => i.status === 'approved')

      if (approvedIssues.length === 0) {
        doc.fontSize(11).font('Helvetica').fillColor('#7a6a55')
          .text('No approved issues to report today.', { align: 'center' })
          .moveDown(1)
          .text('All inspected areas are in satisfactory condition.', { align: 'center' })
      } else {
        doc.fontSize(10).font('Helvetica').fillColor('#7a6a55')
          .text(`Total Approved Issues: ${approvedIssues.length}`, { continued: true })
          .fillColor('#16a34a')
          .text(` ✓`)
        doc.moveDown(0.5)

        approvedIssues.forEach((issue: Issue, index: number) => {
          // Page break check
          if (doc.y > 680) {
            addFooter(currentPage, 3)
            doc.addPage()
            currentPage++
            addHeader()
            doc
              .fontSize(14)
              .font('Helvetica-Bold')
              .fillColor('#1a1208')
              .text('Detailed Issue Report (continued)', { underline: true })
              .moveDown(0.5)
          }

          const issueStartY = doc.y

          doc
            .fontSize(11)
            .font('Helvetica-Bold')
            .fillColor('#B4651E')
            .text(`Issue #${index + 1}`, 50, issueStartY, { continued: true })
            .font('Helvetica')
            .fillColor('#1a1208')
            .text(` | ${issue.block} - Floor ${issue.floor}${issue.room_number ? `, Room ${issue.room_number}` : ''}`)

          doc.moveDown(0.3)

          doc.fontSize(10).font('Helvetica-Bold').fillColor('#1a1208')
            .text('Type:', { continued: true })
            .font('Helvetica').fillColor('#7a6a55')
            .text(` ${issue.issue_type}`)

          doc.fontSize(10).font('Helvetica-Bold').fillColor('#1a1208')
            .text('Description:', { continued: true })
            .font('Helvetica').fillColor('#1a1208')
            .text(` ${issue.description}`, { width: 480 })

          doc.moveDown(0.3)

          if (issue.room_location) {
            doc.fontSize(9).font('Helvetica').fillColor('#7a6a55')
              .text(`Location: ${issue.room_location}`)
          }

          doc.fontSize(9)
            .text(`Reported by: ${issue.marshal_name} (ID: ${issue.marshal_id})`, { continued: true })
            .text(`| ${new Date(issue.reported_at).toLocaleString('en-IN')}`)

          if (issue.is_movable) {
            doc.fillColor('#dc2626')
              .font('Helvetica-Bold')
              .text('⚠ MOVABLE ITEM - Requires immediate attention')
            doc.fillColor('#1a1208').font('Helvetica')
          }

          if (issue.images && issue.images.length > 0) {
            doc.fontSize(9).fillColor('#B4651E')
              .text(`📷 ${issue.images.length} photo(s) attached - View in Excel report for links`)
          }

          doc.moveDown(0.5)
          doc.moveTo(50, doc.y).lineTo(570, doc.y).strokeColor('#e5e5e5').lineWidth(1).stroke()
          doc.moveDown(0.5)
        })
      }

      // Denied Issues Section
      const deniedIssues = data.issues.filter((i: Issue) => i.status === 'denied')
      if (deniedIssues.length > 0) {
        if (doc.y > 600) {
          addFooter(currentPage, 3)
          doc.addPage()
          currentPage++
          addHeader()
        }

        doc
          .moveDown(1)
          .fontSize(14)
          .font('Helvetica-Bold')
          .fillColor('#1a1208')
          .text('Denied Issues', { underline: true })
          .moveDown(0.5)

        doc.fontSize(10).font('Helvetica').fillColor('#7a6a55')
          .text(`Total Denied Issues: ${deniedIssues.length}`)
        doc.moveDown(0.5)

        deniedIssues.forEach((issue: Issue, index: number) => {
          doc.fontSize(10)
            .font('Helvetica-Bold').fillColor('#1a1208')
            .text(`${index + 1}.`, { continued: true })
            .font('Helvetica').fillColor('#7a6a55')
            .text(` ${issue.issue_type} - ${issue.block}/F${issue.floor}${issue.room_number ? `/R${issue.room_number}` : ''}`)
          doc.fontSize(9).fillColor('#7a6a55')
            .text(`   ${issue.description}`, { width: 480 })
          doc.moveDown(0.3)
        })
      }

      // Final footer
      addFooter(currentPage, currentPage)

      doc.moveDown(1)
      doc.moveTo(40, 50).lineTo(570, 50).strokeColor('#B4651E').lineWidth(1).stroke()
      doc.moveDown(0.5)
      doc.fontSize(9).font('Helvetica').fillColor('#7a6a55')
        .text('Generated by MAHE Facility Management System', { align: 'center' })
        .text(`Generated: ${new Date().toLocaleString('en-IN')}`, { align: 'center' })

      doc.end()

    } catch (error) {
      reject(error)
    }
  })
}